/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/
module

public import HexGraphIso.Nauty.Sparse.GeneratedComplete
import all HexGraphIso.Nauty.Sparse.MaxFirstContext
import all HexGraphIso.Nauty.Sparse.MaxFrame
import all HexGraphIso.Nauty.Sparse.GenerationTrace
import all HexGraphIso.Nauty.Sparse.Search
import all HexGraphIso.Sparse.Run
import all HexGraphIso.Generated
import all HexGraphIso.Nauty.Search.State

public section

namespace Hex.GraphIso.Nauty.Sparse

/-- The complete generator trace of the executed sparse search generates
every colour-preserving automorphism, including at order zero. No second
search or assumed recursive correctness contract is used. -/
theorem runColored_generates (G : GraphIso.Sparse.Colored n k) {p : Perm n}
    (hp : GraphIso.Sparse.IsIso G G p) : Perm.Generated (runColored G).generators p := by
  rcases Nat.eq_zero_or_pos n with hn | hn
  · subst n
    have he : p = Perm.id 0 := Perm.ext (fun v => Fin.elim0 v)
    rw [he]
    exact .id
  · let partition := initialPartitionWith n k G.coloring.cells.toArray Fin.val
    obtain ⟨last, leaf, path, _, _⟩ := initial_path G hn
    have h := Max.FirstInput.initial G hn 100
    have ht := Generation.root G
    change Generation.Realizes G (runColored G).generators
      (runState (.ofGraph G.graph) partition.1 partition.2).2.genTrace.toList at ht
    rw [runState, ite_eq_right (by simpa using Nat.ne_of_gt hn)] at ht
    exact h.generates path (by change n + 1 ≤ 1 + (n + 2); omega) (base := []) (by
      intro b
      change (VSet.empty : VSet n).mem b.val = true ↔ b ∈ ([] : List (Fin n))
      simp) ht p hp (Perm.Fixes.nil p)

/-- Membership in the subgroup generated by the actual sparse output is
equivalent to being an automorphism of the native ordered-colour graph. -/
theorem generated_iff (G : GraphIso.Sparse.Colored n k) (p : Perm n) :
    Perm.Generated (runColored G).generators p ↔ GraphIso.Sparse.IsIso G G p := by
  constructor
  · intro hp
    apply (GraphIso.Sparse.isIso_toDense G G p).mp
    exact hp.isIso (fun q hq => (GraphIso.Sparse.isIso_toDense G G q).mpr
      ((runColored_trace G).generator hq))
  · exact runColored_generates G

end Hex.GraphIso.Nauty.Sparse
