/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/
module

public import HexGraphIso.Nauty.Sparse.GeneratedHead
import all HexGraphIso.Nauty.Sparse.MaxFirstContext
import all HexGraphIso.Nauty.Sparse.MaxFirstEntry
import all HexGraphIso.Nauty.Sparse.MaxFirstResume
import all HexGraphIso.Nauty.Sparse.MaxLoop
import all HexGraphIso.Nauty.Sparse.MaxCell
import all HexGraphIso.Nauty.Sparse.MaxFrame
import all HexGraphIso.Nauty.Sparse.MaxParent
import all HexGraphIso.Nauty.Sparse.MaxPrepare
import all HexGraphIso.Nauty.Sparse.Search
import all HexGraphIso.Nauty.Policy.Generated.Trace
import all HexGraphIso.Generated
import all HexGraphIso.Nauty.Search.State

public section

namespace Hex.GraphIso.Nauty.Sparse.Max

/-- Every sparse automorphism fixing the actual individualized base is
generated by the first call's emitted trace. The induction uses the
executed guiding child and its proved complete stabilizer-orbit coverage. -/
theorem FirstInput.generates {G : GraphIso.Sparse.Colored n k} {tcLevel fuel last : Nat}
    {f : Frame n} {leaf : State n} {parents : Parents n}
    {base : List (Fin n)} {gs : List (Perm n)}
    (h : FirstInput G tcLevel f parents)
    (path : Generic.FirstPath (.ofGraph G.graph) tcLevel fuel f.level f.numcells f.entry last leaf)
    (hf : n + 1 ≤ f.level + fuel)
    (hbase : ∀ b : Fin n, f.entry.fixedpts.mem b.val = true ↔ b ∈ base)
    (htrace : Generation.Realizes G gs
      (Generic.node true (.ofGraph G.graph) (n + 2) tcLevel fuel f.level f.numcells f.entry).2.genTrace.toList) :
    ∀ p, GraphIso.Sparse.IsIso G G p → Perm.Fixes base p → Perm.Generated gs p := by
  obtain ⟨level, numcells, codes, st⟩ := f
  induction fuel generalizing level numcells codes st last leaf parents base with
  | zero => cases path
  | succ fuel ih =>
    let f : Frame n := ⟨level, numcells, codes, st⟩
    cases path with
    | @leaf _ _ _ _ hd =>
      intro p hp hfix
      exact Generation.first_terminal h hd hbase hp hfix
    | @step _ _ _ _ _ _ tv hopen htv horbit path =>
      let g := Graph.ofGraph G.graph
      let r := Generic.prepareFirst g tcLevel level numcells st
      let l : Loop n := ⟨f, true⟩
      let c := l.cell G.graph tcLevel
      let p := f.firstParent G.graph tcLevel [] tv
      let ch := p.child G.graph tcLevel
      let raw := Generic.node true g (n + 2) tcLevel fuel ch.level ch.numcells ch.entry
      let left := (policy (n := n)).leaveChild tv (afterChildFirst level tv raw.2)
      let back := p.firstBack G.graph tcLevel fuel
      let guide : Fin n := ⟨tv, VSet.mem_lt (VSet.nextElem_mem htv)⟩
      have hn : 0 < n := by have := h.entry.frame.positive; have := h.entry.frame.depth; omega
      have hi : (visit g level numcells st).1 < n := by
        have hr := h.entry.frame.node.visit_ready hn h.entry.frame.positive
        have hc : (visit g level numcells st).1 = bcount (visit g level numcells st).2.2.ptn level n := hr.ok.count
        have hb := bcount_le (visit g level numcells st).2.2.ptn level n
        change (visit g level numcells st).1 ≠ n at hopen
        omega
      have hbudget : n ≤ level + fuel := by change n + 1 ≤ level + (fuel + 1) at hf; omega
      have hch : FirstInput G tcLevel ch (parents.push p) := h.child hi htv
      have hfixed : p.state.fixedpts = st.fixedpts := by
        change (cheapCheck true level r.2.2.2.2).fixedpts = st.fixedpts
        rw [cheap_fixed]
        exact target_fixed true g tcLevel level r.1
          (recordFirst level (f.code G.graph) (visit g level numcells st).2.2)
      have hbaseChild : ∀ b : Fin n, ch.entry.fixedpts.mem b.val = true ↔ b ∈ guide :: base := by
        intro b
        change (p.state.fixedpts.insert guide.val).mem b.val = true ↔ b ∈ guide :: base
        rw [VSet.mem_insert, hfixed]
        simp only [Bool.or_eq_true, Bool.and_eq_true, beq_iff_eq, decide_eq_true_eq, List.mem_cons]
        rw [hbase]
        constructor
        · rintro (hb | ⟨he, _⟩)
          · exact Or.inr hb
          · exact Or.inl (Fin.ext he.symm)
        · rintro (rfl | hb)
          · exact Or.inr ⟨rfl, guide.isLt⟩
          · exact Or.inl hb
      obtain ⟨bs, fs, _, _, _, hsuffix⟩ := h.suffix hi htv horbit path hbudget
      have htraceTail : Generation.Realizes G gs
          (Generic.sweep true g (n + 2) tcLevel fuel n level c.numcells p.tc tv
            (p.cell.nextElem (some tv)) p.cell (if back.orbits[tv]! == tv then 1 else 0) back).2.2.genTrace.toList := by
        rw [← hsuffix]
        apply htrace.mono
        intro gamma hg
        exact Array.mem_toList_iff.mpr (f.first_contains hopen htv (Array.mem_toList_iff.mp hg))
      have htraceChild : Generation.Realizes G gs raw.2.genTrace.toList := by
        apply htraceTail.mono
        intro gamma hg
        have hb : gamma ∈ back.genTrace := (tracePolicy g (n + 2) tcLevel gamma).recover
          level left (Array.mem_toList_iff.mp hg)
        exact Array.mem_toList_iff.mpr (sweep_contains true g (n + 2) tcLevel fuel n level c.numcells p.tc tv
          (if back.orbits[tv]! == tv then 1 else 0) _ p.cell back hb)
      have hdeep := ih (level := ch.level) (numcells := ch.numcells) (codes := ch.codes) (st := ch.entry)
        hch path (by change n + 1 ≤ level + 1 + fuel; omega) hbaseChild htraceChild
      have hcover := h.orbit hi htv horbit path hbudget hbase htrace
      intro q hq hfix
      apply Perm.Generated.of_stabilizer (G := G.toDense)
        (fun p hp => hdeep p ((GraphIso.Sparse.isIso_toDense G G p).mp hp)) _
        ((GraphIso.Sparse.isIso_toDense G G q).mpr hq) hfix
      intro p hp hpfix
      exact hcover (p.get guide) ⟨p, hp, hpfix, rfl⟩

end Hex.GraphIso.Nauty.Sparse.Max
