/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexGraphIso.Iso

public section

namespace Hex.GraphIso.Perm

variable {n : Nat}

/-- Membership in the subgroup generated by a list of permutations. This
relation is proof data only; computing generators does not construct it. -/
inductive Generated (gens : List (Perm n)) : Perm n → Prop
  | id : Generated gens (Perm.id n)
  | mem {p} : p ∈ gens → Generated gens p
  | comp {p q} : Generated gens p → Generated gens q → Generated gens (p.comp q)
  | inv {p} : Generated gens p → Generated gens p.inv

namespace Generated

/-- A subgroup containing the generators contains every generated element. -/
theorem induction {gens : List (Perm n)} {P : Perm n → Prop}
    (hid : P (Perm.id n)) (hmem : ∀ p ∈ gens, P p)
    (hcomp : ∀ p q, P p → P q → P (p.comp q))
    (hinv : ∀ p, P p → P p.inv) {p : Perm n} (hp : Generated gens p) : P p := by
  induction hp with
  | id => exact hid
  | mem h => exact hmem _ h
  | comp _ _ ihp ihq => exact hcomp _ _ ihp ihq
  | inv _ ih => exact hinv _ ih

/-- Replacing each generator by a word in another list preserves membership. -/
theorem map {s t : List (Perm n)} (h : ∀ p ∈ s, Generated t p)
    {p : Perm n} (hp : Generated s p) : Generated t p :=
  hp.induction .id h (fun _ _ => .comp) (fun _ => .inv)

theorem mono {s t : List (Perm n)} (h : ∀ p ∈ s, p ∈ t)
    {p : Perm n} (hp : Generated s p) : Generated t p :=
  hp.map fun p hp => .mem (h p hp)

/-- Words in automorphisms are automorphisms. -/
theorem isIso {k : Nat} {G : Colored n k} {gens : List (Perm n)}
    (h : ∀ p ∈ gens, IsIso G G p) {p : Perm n} (hp : Generated gens p) :
    IsIso G G p :=
  hp.induction (IsIso.refl G) h (fun _ _ hp hq => hq.trans hp)
    (fun _ hp => hp.symm)

/-- Words in permutations fixing a point also fix that point. -/
theorem fixes {gens : List (Perm n)} {v : Fin n}
    (h : ∀ p ∈ gens, p.get v = v) {p : Perm n} (hp : Generated gens p) :
    p.get v = v := by
  apply hp.induction
  · simp
  · exact h
  · intro p q hp hq
    simp [hp, hq]
  · intro p hp
    exact p.get_inj (by simpa using hp.symm)

end Generated

/-- The pointwise stabilizer condition for a list of base points. -/
def Fixes (base : List (Fin n)) (p : Perm n) : Prop :=
  ∀ v ∈ base, p.get v = v

namespace Fixes

theorem id (base : List (Fin n)) : Fixes base (Perm.id n) := by
  intro v _
  simp

theorem comp {base : List (Fin n)} {p q : Perm n}
    (hp : Fixes base p) (hq : Fixes base q) : Fixes base (p.comp q) := by
  intro v hv
  simp [hp v hv, hq v hv]

theorem inv {base : List (Fin n)} {p : Perm n}
    (hp : Fixes base p) : Fixes base p.inv := by
  intro v hv
  exact p.get_inj (by simpa using (hp v hv).symm)

theorem cons {base : List (Fin n)} {p : Perm n} {v : Fin n} :
    Fixes (v :: base) p ↔ p.get v = v ∧ Fixes base p := by
  simp [Fixes, List.mem_cons, forall_eq_or_imp]

theorem nil (p : Perm n) : Fixes [] p := by
  intro v hv
  cases hv

end Fixes

namespace Generated

/-- A point-stabilizer step in the generation proof. To generate the
stabilizer of `base`, it suffices to generate the stabilizer of the next
point and to represent every image of that point. All membership claims
use the same final generator list. -/
theorem of_stabilizer {k : Nat} {G : Colored n k} {gens : List (Perm n)}
    {base : List (Fin n)} {v : Fin n}
    (hnext : ∀ p, IsIso G G p → Fixes (v :: base) p → Generated gens p)
    (himages : ∀ p, IsIso G G p → Fixes base p →
      ∃ q, Generated gens q ∧ IsIso G G q ∧ Fixes base q ∧ q.get v = p.get v)
    {p : Perm n} (hp : IsIso G G p) (hfix : Fixes base p) :
    Generated gens p := by
  obtain ⟨q, hq, hqiso, hqfix, hv⟩ := himages p hp hfix
  have hrest : Fixes (v :: base) (q.inv.comp p) := by
    apply Fixes.cons.mpr
    refine ⟨?_, hqfix.inv.comp hfix⟩
    rw [get_comp, ← hv, inv_get_get]
  have hg := hnext (q.inv.comp p) (hp.trans hqiso.symm) hrest
  simpa [← comp_assoc] using hq.comp hg

end Generated

end Hex.GraphIso.Perm
