/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexGraphIso.Uncolored
public import HexGraphIso.AutComplete

public section

namespace Hex.Graph

variable {n : Nat}

/-- Completeness: every graph automorphism is generated by the returned list. -/
theorem autos_complete (G : Graph n) (h : 0 < n) {p : GraphIso.Perm n}
    (hp : IsIso G G p) : GraphIso.Perm.Generated (autos G h).gens p :=
  GraphIso.autos_complete _ ((isIso_singleColor_iff G G p h).mpr hp)

/-- Two vertices have the same representative exactly when they are
in the same automorphism orbit. -/
theorem autos_sameOrbit (G : Graph n) (h : 0 < n) (u v : Fin n) :
    (autos G h).orbits[u.val]! = (autos G h).orbits[v.val]! ↔ SameOrbit G u v :=
  (GraphIso.autos_sameOrbit _ u v).trans (sameOrbit_singleColor_iff G u v h)

end Hex.Graph
