/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexGraphIso.Nauty.Correct.Generation.HeadCoverage
import all HexGraphIso.Nauty.Correct.Generation.Trace
import all HexGraphIso.Nauty.Search.Search
import all HexGraphIso.Generated
import all HexGraphIso.Nauty.Correct.Generation.Carry

public section

namespace Hex.GraphIso.Nauty.Generation

variable {n k : Nat}

/-- The first-path stabilizer induction. Every automorphism fixing the
individualized base is generated by the final public list, provided the
actual node's trace is included in that list's raw trace. -/
theorem first_generates (G : Colored n k) (tcLevel : Nat) :
    ∀ fuel level numcells (codes : List Nat) (st : SearchSt n) (trail : FrameTrail) (base : List (Fin n)),
      FirstInv G { g := rowsOf G } level codes numcells st trail →
      PathOk { g := rowsOf G } (initPtn n (n + 2) (initialPartition G).2)
        (initialPartition G).1 level st →
      st.noncheaplevel ≤ level →
      CheapDesc { g := rowsOf G } level st.noncheaplevel
        (refine { g := rowsOf G } level st.lab st.ptn st.active numcells) →
      OrbSound (OrbConn st.genTrace.toList n) st.orbits n →
      1 ≤ level → level = codes.length + 1 → st.firsttc.size = n + 2 → n + 2 < level + fuel →
      (∀ b : Fin n, st.fixedpts.mem b.val = true ↔ b ∈ base) →
      (∀ γ ∈ (firstPathNode { g := rowsOf G } (n + 2) tcLevel fuel level numcells st).2.genTrace,
        γ ∈ Aut.trace G) →
      ∀ p, IsIso G G p → Perm.Fixes base p → Perm.Generated (Aut.gens G) p := by
  intro fuel
  induction fuel with
  | zero =>
    intro level numcells codes st trail base hfirst _ _ _ _ _ _ _ hfuel
    have := hfirst.searchOk.levelLe
    omega
  | succ fuel ih =>
    intro level numcells codes st trail base hfirst hpathOk hcheap hdesc horb hlevel hpath htcsize hfuel
      hbase htrace p hp hfix
    let ctx : Ctx n := { g := rowsOf G }
    let rs := refine ctx level st.lab st.ptn st.active numcells
    have hn0 : 0 < n := by have := hfirst.searchOk.levelLe; omega
    obtain ⟨hit, heqt, hcount⟩ := hfirst.refined rfl hn0 hlevel
    by_cases hnum : rs.numcells = n
    · have hpathRef := hpathOk.refine hn0 hlevel (size_rowsOf G) hfirst.searchOk hfirst.activeStarts
      have hok := refine_searchOk hn0 hfirst.searchOk hlevel
        (st2 := { st with lab := rs.lab, ptn := rs.ptn, active := rs.active }) rfl rfl (Or.inl rfl)
      have hd := (refine_discrete_iff hn0 hfirst.searchOk hlevel).mp hnum
      have he := terminal hpathRef.stab hit.ok.labSize
        (achieved_perm_range hit.ok.labSize hn0 hok.reach) hit.ok.ptnSize hit.ok.ptnEnd hd hp
        (fun b hb => hfix b ((hbase b).mp hb))
      rw [he]
      exact .id
    · have hnumLt : rs.numcells < n := Nat.lt_of_le_of_ne (hcount ▸ bcount_le _ _ _) hnum
      have hl := hfirst.searchOk.levelLe
      obtain ⟨tc, len, hlen, hrange, hmk, hhead⟩ := hfirst.head
        (ctx := ctx) (tcLevel := tcLevel) (runFuel := fuel) (specFuel := n - level)
        rfl rfl hlevel hpath (by omega) (by omega) hcheap hdesc hpathOk horb hnumLt
      let cell := windowSet n rs.lab tc len
      let pre := firstStart ctx level numcells tc len st
      let guideVal := (cell.nextElem none).getD 0
      have htcPre : pre.firsttc.size = n + 2 := by
        dsimp only [pre, firstStart]
        split <;> simpa only [Array.size_set!] using htcsize
      have hfixedPre : pre.fixedpts = st.fixedpts := by
        dsimp only [pre, firstStart]
        split <;> rfl
      have htraceLoop : ∀ γ ∈ (firstChildLoop ctx (n + 2) tcLevel fuel (n + 1) level rs.numcells tc
          guideVal (cell.nextElem none) cell 0 pre).2.2.genTrace, γ ∈ Aut.trace G := by
        intro γ hγ
        apply htrace
        rw [firstPath_internal_state ctx (n + 2) tcLevel fuel level numcells st hnum, hmk]
        dsimp only
        rw [worksetOf_eq_windowSet _ tc len (by omega)]
        change γ ∈ (match (firstChildLoop ctx (n + 2) tcLevel fuel (n + 1) level rs.numcells tc
            guideVal (cell.nextElem none) cell 0 pre).1 with
          | some r => (r, (firstChildLoop ctx (n + 2) tcLevel fuel (n + 1) level rs.numcells tc
              guideVal (cell.nextElem none) cell 0 pre).2.2)
          | none => (Int.ofNat level - 1, firstFinish level len
              (firstChildLoop ctx (n + 2) tcLevel fuel (n + 1) level rs.numcells tc
                guideVal (cell.nextElem none) cell 0 pre).2.1
              (firstChildLoop ctx (n + 2) tcLevel fuel (n + 1) level rs.numcells tc
                guideVal (cell.nextElem none) cell 0 pre).2.2)).2.genTrace
        generalize he : firstChildLoop ctx (n + 2) tcLevel fuel (n + 1) level rs.numcells tc
          guideVal (cell.nextElem none) cell 0 pre = result at hγ ⊢
        obtain ⟨r, index, out⟩ := result
        cases r <;> dsimp only at hγ ⊢
        · unfold firstFinish
          split <;> exact hγ
        · exact hγ
      have hhead' := hhead
      cases hhead with
      | @intro offset child out r fs best eventTrail hnext horbit hlab hptn hpathPre hoff hat
          hchild hfirstChild hpathChild hcheapChild hdescChild horbitsChild hcall hchildRun hkeep tail =>
        let guide : Fin n := ⟨guideVal, VSet.mem_lt (VSet.nextElem_mem hnext)⟩
        have htcChild : child.firsttc.size = n + 2 := by rw [hchild]; exact htcPre
        have hbaseChild : ∀ b : Fin n, child.fixedpts.mem b.val = true ↔ b ∈ guide :: base := by
          intro b
          rw [hchild]
          change (pre.fixedpts.insert guide.val).mem b.val = true ↔ b ∈ guide :: base
          rw [VSet.mem_insert, hfixedPre]
          simp only [Bool.or_eq_true, Bool.and_eq_true, beq_iff_eq, decide_eq_true_eq, List.mem_cons]
          rw [hbase]
          constructor
          · rintro (hb | ⟨he, _⟩)
            · exact Or.inr hb
            · exact Or.inl (Fin.ext he.symm)
          · rintro (rfl | hb)
            · exact Or.inr ⟨rfl, guide.isLt⟩
            · exact Or.inl hb
        have htraceChild : ∀ γ ∈ (firstPathNode ctx (n + 2) tcLevel fuel (level + 1)
            (rs.numcells + 1) child).2.genTrace, γ ∈ Aut.trace G := by
          intro γ hγ
          rw [hcall] at hγ
          apply htraceLoop
          rw [hnext]
          exact firstGuide_retains (cfuel := n) (index := 0) horbit
            (by rw [← hchild]; exact hcall) hγ
        have hdeep := ih (level + 1) (rs.numcells + 1) (codes ++ [rs.longcode]) child
          (trail.push level ⟨sweepFrame (n - level) (codes ++ [rs.longcode]) rs.lab rs.ptn tc rs.numcells, offset⟩)
          (guide :: base) hfirstChild hpathChild hcheapChild hdescChild horbitsChild (by omega)
          (by simp only [List.length_append, List.length_singleton]; omega) htcChild (by omega)
          hbaseChild htraceChild
        have hcover := hhead'.cover (guide := guide)
          (by simp only [List.length_append, List.length_singleton]; omega) (by omega) htcPre rfl
          (fun b => by rw [hfixedPre]; exact hbase b) hdeep htraceLoop
        apply Perm.Generated.of_stabilizer hdeep _ hp hfix
        intro q hq hqfix
        exact (hcover (q.get guide) ⟨q, hq, hqfix, rfl⟩).witness

end Hex.GraphIso.Nauty.Generation
