/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexGraphIso.AutTrace
public import HexGraphIso.Nauty.Correct.Generation.Stabilizer
import all HexGraphIso.Nauty.Invariant.Autos
import all HexGraphIso.Generated
import all HexGraphIso.Nauty.Search.Search

public section

namespace Hex.GraphIso.Nauty.Generation

variable {n k : Nat}

/-- Each vertex omitted by a pruning pair has a strictly smaller image
under a generated automorphism fixing the pair's fixed points. -/
def PairGenerated (G : Colored n k) (fix mcr : VSet n) : Prop :=
  ∀ v : Fin n, mcr.mem v.val = false → ∃ p : Perm n,
    Perm.Generated (Aut.gens G) p ∧ IsIso G G p ∧
      (∀ u : Fin n, fix.mem u.val = true → p.get u = u) ∧
      (p.get v).val < v.val

/-- The carriers of an explicit pair are powers of its recorded generator,
so they lie in the subgroup generated by the final trace. -/
theorem pair_explicit {G : Colored n k} {γ : Array Nat}
    (hγ : γ ∈ Aut.trace G) :
    PairGenerated G (fmperm γ n).1 (fmperm γ n).2 := by
  have hraw : γ ∈ Aut.raw G := by rw [Aut.raw_eq_trace]; exact hγ
  obtain ⟨p, hp, hval⟩ := Aut.raw_mem hraw
  have hb : ∀ v, v < n → γ[v]! < n := by
    intro v hv
    rw [← hval ⟨v, hv⟩]
    exact (p.get ⟨v, hv⟩).isLt
  have hinj : ∀ a b, a < n → b < n → γ[a]! = γ[b]! → a = b := by
    intro a b ha hb heq
    rw [← hval ⟨a, ha⟩, ← hval ⟨b, hb⟩] at heq
    exact congrArg Fin.val (p.get_inj (Fin.ext heq))
  intro v hv
  obtain ⟨t, ht⟩ := fmperm_mcr hb hinj v.isLt hv
  obtain ⟨q, hq, hqval⟩ := Aut.generated_word (G := G) (List.replicate t γ)
    (fun δ hδ => by rw [List.eq_of_mem_replicate hδ]; exact hraw)
  refine ⟨q, hq, Aut.generated_isIso hq, ?_, ?_⟩
  · intro u hu
    apply Fin.ext
    rw [hqval]
    exact applyWord_replicate_fixed (fmperm_fix hb hinj hu).2 t
  · rw [hqval]
    exact ht

/-- An implicit pair whose fixed points include the next stabilizer base
has generated carriers by the downward stabilizer-chain hypothesis. -/
theorem pair_implicit {G : Colored n k} {fix mcr : VSet n}
    {base : List (Fin n)}
    (hpair : PairOk (rowsOf G)
      (initPtn n (n + 2) (initialPartition G).2) (initialPartition G).1 1 fix mcr)
    (hbase : ∀ v ∈ base, fix.mem v.val = true)
    (hnext : ∀ p, IsIso G G p → Perm.Fixes base p →
      Perm.Generated (Aut.gens G) p) : PairGenerated G fix mcr := by
  intro v hv
  obtain ⟨γ, hcheck, hfix, hstab, hlt⟩ := hpair v.val v.isLt hv
  obtain ⟨p, hp⟩ := Aut.admit_root hcheck hstab
  have hiso := autom?_isIso hp
  have hval := autom?_val_get hp
  have hfixed : ∀ u : Fin n, fix.mem u.val = true → p.get u = u := by
    intro u hu
    exact Fin.ext ((hval u).trans (hfix u.val u.isLt hu))
  refine ⟨p, hnext p hiso (fun u hu => hfixed u (hbase u hu)), hiso, hfixed, ?_⟩
  rw [hval]
  exact hlt

/-- Repeated removal by generated carriers reaches a survivor. The
strictly decreasing vertex index is the same termination argument used by
the executable pruning proof, with subgroup membership retained. -/
theorem pruned_generated {G : Colored n k} {base : List (Fin n)}
    {W R : VSet n}
    (hstable : ∀ p, IsIso G G p → Perm.Fixes base p →
      ∀ v : Fin n, W.mem v.val = true → W.mem (p.get v).val = true)
    (hdrop : ∀ v : Fin n, W.mem v.val = true → R.mem v.val = false →
      ∃ p, Perm.Generated (Aut.gens G) p ∧ IsIso G G p ∧
        Perm.Fixes base p ∧ (p.get v).val < v.val) :
    ∀ v : Fin n, W.mem v.val = true → ∃ p,
      Perm.Generated (Aut.gens G) p ∧ IsIso G G p ∧ Perm.Fixes base p ∧
        W.mem (p.get v).val = true ∧ R.mem (p.get v).val = true := by
  intro v
  have h : ∀ a, ∀ ha : a < n, W.mem a = true → ∃ p,
      Perm.Generated (Aut.gens G) p ∧ IsIso G G p ∧ Perm.Fixes base p ∧
        W.mem (p.get ⟨a, ha⟩).val = true ∧ R.mem (p.get ⟨a, ha⟩).val = true := by
    intro a
    induction a using Nat.strongRecOn with
    | ind a ih =>
      intro ha hW
      cases hR : R.mem a with
      | true => exact ⟨Perm.id n, .id, IsIso.refl G, Perm.Fixes.id base,
          by simpa using hW, by simpa using hR⟩
      | false =>
        obtain ⟨p, hp, hpiso, hpfix, hlt⟩ := hdrop ⟨a, ha⟩ hW hR
        obtain ⟨q, hq, hqiso, hqfix, hWq, hRq⟩ := ih _ hlt (p.get ⟨a, ha⟩).isLt
          (hstable p hpiso hpfix ⟨a, ha⟩ hW)
        exact ⟨q.comp p, hq.comp hp, hpiso.trans hqiso, hqfix.comp hpfix,
          by simpa using hWq, by simpa using hRq⟩
  exact h v.val v.isLt

/-- A short-prune filter retains a representative of every orbit of the
current point stabilizer when its last pair has generated carriers. -/
theorem shortprune_generated {G : Colored n k} {base : List (Fin n)}
    {W : VSet n} {st : SearchSt n}
    (hstable : ∀ p, IsIso G G p → Perm.Fixes base p →
      ∀ v : Fin n, W.mem v.val = true → W.mem (p.get v).val = true)
    (hlast : ∀ fix mcr, st.autos.back? = some (fix, mcr) →
      PairGenerated G fix mcr ∧ ∀ v ∈ base, fix.mem v.val = true) :
    ∀ v : Fin n, W.mem v.val = true → ∃ p,
      Perm.Generated (Aut.gens G) p ∧ IsIso G G p ∧ Perm.Fixes base p ∧
        W.mem (p.get v).val = true ∧ (shortprune W st).mem (p.get v).val = true := by
  apply pruned_generated hstable
  intro v hW hR
  rw [shortprune] at hR
  split at hR
  · next fix mcr heq =>
    obtain ⟨hpair, hbase⟩ := hlast fix mcr heq
    rw [VSet.mem_inter, hW, Bool.true_and] at hR
    obtain ⟨p, hp, hiso, hfix, hlt⟩ := hpair v hR
    exact ⟨p, hp, hiso, fun u hu => hfix u (hbase u hu), hlt⟩
  · rw [hW] at hR
    cases hR

end Hex.GraphIso.Nauty.Generation
