/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexGraphIso.Nauty.Policy.KeyComplete
public import HexGraphIso.Nauty.Policy.First.Root
public import HexGraphIso.Nauty.Policy.Generated.Root
public import HexGraphIso.Nauty.Policy.Result
import all HexGraphIso.Nauty.Policy.Max.Combine
import all HexGraphIso.Nauty.Policy.Max.Rules
import all HexGraphIso.Nauty.Policy.Max.Contract
import all HexGraphIso.Nauty.Policy.Generic.Calls
import all HexGraphIso.Nauty.Policy.Generated.Root
import all HexGraphIso.Nauty.Search.Search
import all HexGraphIso.Nauty.Search.State

public section

namespace Hex.GraphIso.Nauty

/-- Every automorphism is generated by the search's own
checked output trace, including for the empty graph. -/
theorem generators_complete {n k : Nat} {G : Colored n k} {p : Perm n}
    (hp : IsIso G G p) :
    Perm.Generated ((runColoredTraced G).autos.toList.filterMap (autom? G)) p := by
  rcases Nat.eq_zero_or_pos n with hn | hn
  · subst n
    exact Max.zero_generates G p
  · apply Max.root_generates G hn _ hp
    intro fuel _ first level numcells st _
    exact Generic.node_calls (Max.rules G 100).calls first fuel level numcells st trivial

end Hex.GraphIso.Nauty
